import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import { inter } from "./fonts";
import Footer from "@/components/navigation/footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "MJP Web Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-background text-white h-full selection:bg-primary/80">
      <body className={`${inter.className} flex flex-col h-full`}>
        <Navigation />
        <span className="pt-[160px]" />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
