import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import { inter } from "./fonts";
import Footer from "@/components/navigation/footer";

export const metadata: Metadata = {
  title: "MJP Web Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navigation />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
